// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Url struct {
	ID          int64         `json:"id"`
	Url         string        `json:"url"`
	Shortcode   string        `json:"shortcode"`
	Createdat   string        `json:"createdat"`
	Updatedat   string        `json:"updatedat"`
	Accesscount sql.NullInt64 `json:"accesscount"`
}
