// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error)
	DeleteURLByShortCode(ctx context.Context, shortcode string) error
	GetURLByShortCode(ctx context.Context, shortcode string) (GetURLByShortCodeRow, error)
	GetURLStatsByShortCode(ctx context.Context, shortcode string) (Url, error)
	IncrementURLAccessCountByShortCode(ctx context.Context, shortcode string) error
	UpdateURLByShortCode(ctx context.Context, arg UpdateURLByShortCodeParams) (UpdateURLByShortCodeRow, error)
}

var _ Querier = (*Queries)(nil)
